name: release

permissions:
  contents: write

on:
  push:
    tags:
    - *

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - run: scripts/build
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          prerelease: ${{ env.IS_PRERELEASE }}
          generate_release_notes: true
