name: validate

on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      - run: go mod tidy
      - run: go fmt ./...
      - run: if [ -n "$(git status --porcelain --untracked-files=no)" ]; then git --no-pager diff; exit 1; fi
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      - run: go test ./...
